### ISSUE TITLE
State of development

### ISSUE THREAD

**Issue by PaulBernier** [andywer/key-store#8]
I was looking for a project like yours, a simple enough code so I can understand exactly what is going on and yet very safe. 

1. I'm wondering if you consider that package production ready? Do you know of any other projects using it? 
2. Am I also understanding correctly that the keys are not encrypted?
3. What does "Isomorphic" means in the description of the project as an "Isomorphic encrypted key store encrypted key store"

Thank you!

**Comment by andywer** [comment]
Hey Paul!
Thanks for the feedback. Sounds like the readme needs to be improved... 😉

1. Yeah, at this point I consider it production ready. We use it for the [Solar wallet](https://solarwallet.io) and appearantly it's being used by [Minespider](https://www.minespider.com/) for an SDK of theirs.
2. For each key you have a public and a private dataset. The private data is strongly encrypted, of course.
3. "Isomorphic" means that you can use it as is on the server-side, in an electron app or in a web client, since it's decoupled from the actual data storage code.

Hope that helps!

**Comment by PaulBernier** [comment]
Thanks Andy, that's exactly what I was hoping to ear!

I'm actually working on a very similar project to Solar, just scratch Stellar, I'm building a ["Simple and secure Factom wallet" ](https://github.com/Factom-Asset-Tokens/wallet/tree/development) (and supporting the tokenization platform built on top). I also went the Electron.js path, so that makes me really confident that this lib is the right choice for our project.

Also interestingly one other result that came out of my research was that [stellar-keystore](https://www.npmjs.com/package/stellar-keystore) package.

Thanks and best of luck with Solar!

**Comment by andywer** [comment]
Thanks for sharing. Also wasn't aware that StellarPort built a similar thing as well ^^

Feel free to keep me posted how Factom turns out and how this package works out for you if you like 😉
